[phases.setup]
nixPkgs = [
  "python311",
  "zlib",
  "libjpeg",
  "libpng",
  "freetype",
  "dejavu_fonts"
]

[phases.install]
cmds = [
  "python3.11 -m venv --copies /opt/venv",
  ". /opt/venv/bin/activate && pip install --upgrade pip && pip install -r requirements.txt"
]
